# Generated by Django 3.2.12 on 2022-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(to='projects.Tag')),
            ],
        ),
    ]
