# Generated by Django 3.2.12 on 2022-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='source',
            field=models.CharField(max_length=250),
        ),
    ]
