# Generated by Django 3.2.12 on 2022-07-16 23:17

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='about/', validators=[about.validators.validate_file_extension]),
        ),
    ]
