# Generated by Django 3.2.12 on 2022-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='about/'),
        ),
    ]
