# Generated by Django 3.2.12 on 2022-03-31 10:18

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='about/', validators=[about.validators.validate_file_extension]),
        ),
    ]
