# Generated by Django 3.2.12 on 2022-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, max_length=255, null=True, upload_to='icons')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
